### ISSUE TITLE
Doesn't support django 3.0

### ISSUE THREAD

**Issue by jszsj** [jsocol/django-jsonview#48]
Can not work with django 3.0:cannot import name 'six' from 'django.utils'
django.utils.six module was removed

**Comment by asterix24** [comment]
I just change import to `import six`, and this enough to work with django 3, in `/usr/local/lib/python3.8/site-packages/jsonview/decorators.py`

**Comment by sebastiaopf** [comment]
This patch makes it work for Django 3.0:

```patch
--- decorators.orig.py	2020-06-09 18:47:56.382376731 -0300
+++ decorators.py	2020-06-09 18:48:20.946144364 -0300
@@ -11,7 +11,7 @@
 from django.core.handlers.base import BaseHandler
 from django.core.serializers.json import DjangoJSONEncoder
 from django.core.signals import got_request_exception
-from django.utils import six
+import six
 from django.utils.module_loading import import_string
 
 from .exceptions import BadRequest

```

**Comment by jsocol** [comment]
The version on main is Py3 only and doesn't depend on six at all. I'm working on getting a new release packaged up.
